[default]
locale = 'en-gb'
extend-ignore-re = [
	"(?s)(#|//)\\s*spellchecker:off.*?\\n\\s*(#|//)\\s*spellchecker:on",
	"(?s)<!--\\s*spellchecker:off.*?\\n\\s*spellchecker:on\\s*-->",
	"(?Rm)^.*#\\s*spellchecker:disable-line$",
	"(?m)^.*<!--\\s*spellchecker:disable-line\\s*-->\\n.*$",
]

[default.extend-words]
Organization = 'Organization'
center = 'center'

[files]
extend-exclude = ['*.svg', '*.png', '*.json']
